# Generated by Django 4.1 on 2022-09-21 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_alter_article_options_alter_comment_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='image_height',
            field=models.SmallIntegerField(default=200),
        ),
        migrations.AddField(
            model_name='image',
            name='image_width',
            field=models.SmallIntegerField(default=200),
        ),
        migrations.AlterField(
            model_name='image',
            name='image_article',
            field=models.ImageField(height_field='image_height', upload_to='', verbose_name='Изображение к статье', width_field='image_width'),
        ),
    ]
